name: Publish package

on:
  push:
    tags: ['*']

permissions:
  attestations: write
  id-token: write
  packages: write
  security-events: read

jobs:
  fedora-matrix:
    name: Fedora matrix
    runs-on: ubuntu-latest
    steps:
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v6.0.2
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0

      - id: get-latest-fedora-version
        name: Get latest Fedora version
        run: |
          sed -nE "s|^ARG FEDORA_VERSION=(.*)$|latest_fedora_version=\1|p" Containerfile >> $GITHUB_OUTPUT

      - id: list-fedora-versions
        name: List Fedora versions
        run: |
          latest_fedora_version=${{ steps.get-latest-fedora-version.outputs.latest_fedora_version }}
          echo list_fedora_versions=[${{ steps.get-latest-fedora-version.outputs.latest_fedora_version }},$(( latest_fedora_version - 1 )),$(( latest_fedora_version - 2 ))] >> "$GITHUB_OUTPUT"

    outputs:
      fedora_versions: ${{ steps.list-fedora-versions.outputs.list_fedora_versions }}
      latest_fedora_version: ${{ steps.get-latest-fedora-version.outputs.latest_fedora_version }}

  publish-package:
    name: Publish package
    runs-on: ubuntu-latest
    needs: fedora-matrix
    strategy:
      matrix:
        fedora_version: ${{ fromJSON(needs.fedora-matrix.outputs.fedora_versions) }}
    steps:
      - id: publish-package
        name: Publish package
        uses: nedix/actions/publish-package@main
        with:
          build_arguments: |
            FEDORA_VERSION=${{ matrix.fedora_version }}
          cache_tag: "cache${{ matrix.fedora_version }}"
          enable_cache: 'true'
          enable_latest_tag: ${{ matrix.fedora_version == needs.fedora-matrix.outputs.latest_fedora_version && 'true' || 'false' }}
          enable_short_sha_tag: 'false'
          enable_version_tag: 'false'
          platforms: linux/amd64,linux/arm64/v8
          registry: ${{ secrets.REGISTRY_DOMAIN || 'ghcr.io' }}
          registry_path: ${{ secrets.REGISTRY_PATH || github.repository }}
          registry_username: ${{ secrets.REGISTRY_USERNAME || github.actor }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD || github.token }}
          tags: |
            fedora${{ matrix.fedora_version }}
