name: Update package

on:
  push:
    tags: ['*']

permissions:
  attestations: write
  id-token: write
  packages: write
  security-events: write

jobs:
  fedora-matrix:
    name: Fedora matrix
    runs-on: ubuntu-latest
    steps:
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v6.0.2
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0

      - id: get-latest-fedora-version
        name: Get latest Fedora version
        run: |
          echo "latest_fedora_version=" && sed -nE "s|^ARG FEDORA_VERSION=(.*)$|latest_fedora_version=\1|p" Containerfile >> "$GITHUB_OUTPUT"

      - id: get-previous-fedora-version
        name: Get previous Fedora version
        run: |
          latest_fedora_version=${{ steps.get-latest-fedora-version.outputs.latest_fedora_version }}
          echo previous_fedora_version=$(( latest_fedora_version - 1 )) >> "$GITHUB_OUTPUT"

      - id: get-oldest-fedora-version
        name: Get oldest Fedora version
        run: |
          latest_fedora_version=${{ steps.get-latest-fedora-version.outputs.latest_fedora_version }}
          echo oldest_fedora_version=$(( latest_fedora_version - 2 )) >> "$GITHUB_OUTPUT"

    outputs:
      latest_fedora_version: ${{ steps.get-upper-fedora-version.outputs.latest_fedora_version }}
      previous_fedora_version: ${{ steps.get-previous-fedora-version.outputs.previous_fedora_version }}
      oldest_fedora_version: ${{ steps.get-oldest-fedora-version.outputs.oldest_fedora_version }}
      fedora_versions: ${{ steps.get-oldest-fedora-version.outputs.oldest_fedora_version }} ${{ steps.get-previous-fedora-version.outputs.previous_fedora_version }} ${{ steps.get-upper-fedora-version.outputs.latest_fedora_version }}

  update-package:
    name: Update package
    runs-on: ubuntu-latest
    needs: fedora-matrix
    strategy:
      matrix:
        fedora_version: ${{ fromJSON(needs.fedora-matrix.outputs.fedora_versions) }}
    steps:
      - id: update-package
        name: Update package
        uses: nedix/actions/update-package@main
        with:
          enable_latest_tag: ${{ matrix.fedora_version == needs.fedora-matrix.outputs.latest_fedora_version && 'true' || 'false' }}
          enable_short_sha_tag: 'false'
          enable_version_tag: 'false'
          platforms: 'linux/amd64,linux/arm64/v8'
          registry: ${{ secrets.REGISTRY_DOMAIN || 'ghcr.io' }}
          registry_path: ${{ secrets.REGISTRY_PATH || github.repository }}
          registry_username: ${{ secrets.REGISTRY_USERNAME || github.actor }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD || github.token }}
          tags: |
            ${{ matrix.fedora_version }}
